@startditaa
+--------+     +---------+     +---------+
| Client |---->|   API   |---->|  Order  |
|  cBLU  |     | Gateway |     | Service |
+--------+     +---------+     +----+----+
                                    |
                                    v
                               +----+-----+
                               | Database |
                               |   cGRE   |
                               +----------+
@endditaa
